[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function


markers =
    smoke: mark test as smoke test (quick validation)
    negative: mark test as negative test (error handling)
    api: mark test as API test
    ui: mark test as UI/e2e test
    regression: all test cases

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

retries = 2
retry_delay = 1 

addopts = 
    --html=reports/report.html 
    --self-contained-html 
    --capture=no 
    --color=yes 
    -v
    